### ISSUE TITLE
44

### ISSUE THREAD

**Issue by maxogden** [mafintosh/leveldown-prebuilt#4]
iojs 2.0.0 has NODE_MODULE_VERSION 44 now I guess, so we need to publish prebuilts for that

**Comment by maxogden** [comment]
hmm actually it doesnt even compile for me:

```
🐈  npm i
npm WARN package.json dat@6.9.6 No README data
npm WARN engine cuid@1.2.4: wanted: {"node":"~0.x.x"} (current: {"node":"2.0.0","npm":"2.9.0"})
 
> leveldown-prebuilt@1.0.3 install /Users/maxogden/src/js/dat/node_modules/dat-core/node_modules/leveldown-prebuilt
> node-pre-gyp install --fallback-to-build

  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/db_impl.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/db_iter.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/filename.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/dbformat.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/log_reader.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/log_writer.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/memtable.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/repair.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/table_cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/version_edit.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/version_set.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/write_batch.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/helpers/memenv/memenv.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/block_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/filter_block.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/format.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/merger.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/table.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/table_builder.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/two_level_iterator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/arena.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/bloom.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/cache.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/coding.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/comparator.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/crc32c.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/env.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/filter_policy.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/hash.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/logging.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/options.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/status.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/port/port_posix.o
  CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/env_posix.o
  LIBTOOL-STATIC Release/leveldb.a
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-sinksource.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-stubs-internal.o
  CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy.o
  LIBTOOL-STATIC Release/snappy.a
  CXX(target) Release/obj.target/leveldown/src/batch.o
In file included from ../src/batch.cc:3:
In file included from ../node_modules/nan/nan.h:74:
In file included from ../node_modules/nan/nan_new.h:181:
../node_modules/nan/nan_implementation_12_inl.h:172:66: error: too many arguments to function call, expected at most 2, have 4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
         ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/maxogden/.node-gyp/2.0.0/deps/v8/include/v8.h:4188:3: note: 'New' declared here
  static Local<Signature> New(
  ^
1 error generated.
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/maxogden/src/js/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/usr/local/bin/iojs" "/Users/maxogden/src/js/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=leveldown-prebuilt" "--configuration=Release" "--module_name=leveldown" "--version=1.0.3" "--major=1" "--patch=3" "--runtime=node" "--node_abi=node-v44" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=leveldown.js" "--host=https://github.com/mafintosh/node-leveldown/releases/download/v1.0.3/" "--module_path=/Users/maxogden/src/js/dat/node_modules/dat-core/node_modules/leveldown-prebuilt/build-pre-gyp" "--module=/Users/maxogden/src/js/dat/node_modules/dat-core/node_modules/leveldown-prebuilt/build-pre-gyp/leveldown.node" "--package_name=leveldown-v1.0.3-node-v44-darwin-x64.tar.gz" "--staged_tarball=build/stage/leveldown-v1.0.3-node-v44-darwin-x64.tar.gz" "--hosted_path=https://github.com/mafintosh/node-leveldown/releases/download/v1.0.3/" "--hosted_tarball=https://github.com/mafintosh/node-leveldown/releases/download/v1.0.3/leveldown-v1.0.3-node-v44-darwin-x64.tar.gz"
gyp ERR! cwd /Users/maxogden/src/js/dat/node_modules/dat-core/node_modules/leveldown-prebuilt
gyp ERR! node -v v2.0.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/iojs /Users/maxogden/src/js/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=leveldown-prebuilt --configuration=Release --module_name=leveldown --version=1.0.3 --major=1 --patch=3 --runtime=node --node_abi=node-v44 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=leveldown.js --host=https://github.com/mafintosh/node-leveldown/releases/download/v1.0.3/ --module_path=/Users/maxogden/src/js/dat/node_modules/dat-core/node_modules/leveldown-prebuilt/build-pre-gyp --module=/Users/maxogden/src/js/dat/node_modules/dat-core/node_modules/leveldown-prebuilt/build-pre-gyp/leveldown.node --package_name=leveldown-v1.0.3-node-v44-darwin-x64.tar.gz --staged_tarball=build/stage/leveldown-v1.0.3-node-v44-darwin-x64.tar.gz --hosted_path=https://github.com/mafintosh/node-leveldown/releases/download/v1.0.3/ --hosted_tarball=https://github.com/mafintosh/node-leveldown/releases/download/v1.0.3/leveldown-v1.0.3-node-v44-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/maxogden/src/js/dat/node_modules/dat-core/node_modules/leveldown-prebuilt/node_modules/node-pre-gyp/lib/util/compile.js:71:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:953:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1020:5)
node-pre-gyp ERR! System Darwin 14.1.0
node-pre-gyp ERR! command "/usr/local/bin/iojs" "/Users/maxogden/src/js/dat/node_modules/dat-core/node_modules/leveldown-prebuilt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/maxogden/src/js/dat/node_modules/dat-core/node_modules/leveldown-prebuilt
node-pre-gyp ERR! node -v v2.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.2
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/iojs /Users/maxogden/src/js/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=leveldown-prebuilt --configuration=Release --module_name=leveldown --version=1.0.3 --major=1 --patch=3 --runtime=node --node_abi=node-v44 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=leveldown.js --host=https://github.com/mafintosh/node-leveldown/releases/download/v1.0.3/ --module_path=/Users/maxogden/src/js/dat/node_modules/dat-core/node_modules/leveldown-prebuilt/build-pre-gyp --module=/Users/maxogden/src/js/dat/node_modules/dat-core/node_modules/leveldown-prebuilt/build-pre-gyp/leveldown.node --package_name=leveldown-v1.0.3-node-v44-darwin-x64.tar.gz --staged_tarball=build/stage/leveldown-v1.0.3-node-v44-darwin-x64.tar.gz --hosted_path=https://github.com/mafintosh/node-leveldown/releases/download/v1.0.3/ --hosted_tarball=https://github.com/mafintosh/node-leveldown/releases/download/v1.0.3/leveldown-v1.0.3-node-v44-darwin-x64.tar.gz' (1)
npm WARN prefer global standard@3.7.3 should be installed with -g
npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "i"
npm ERR! node v2.0.0
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE

npm ERR! leveldown-prebuilt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown-prebuilt@1.0.3 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the leveldown-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/maxogden/src/js/dat/npm-debug.log
```

**Comment by maxogden** [comment]
compiles fine after upgrading nan to latest, but we still need to do new prebuilts for `44`

**Comment by wyattbiker** [comment]
Anything on this? I am getting an error when I try to use node-inspector:

Error: Cannot find module '/usr/local/lib/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.0/node-v44-darwin-x64/debug.node'
